"""Added is_deleted column to boards table

Revision ID: 490087b83361
Revises: 
Create Date: 2023-07-30 19:36:01.962870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '490087b83361'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('posts', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'created_at')
    op.drop_column('boards', 'is_deleted')
    # ### end Alembic commands ###
