"""Edited board

Revision ID: b98c18aae5e6
Revises: 490087b83361
Create Date: 2023-07-30 20:48:17.695185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98c18aae5e6'
down_revision = '490087b83361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
